---
# Homepage configuration
# See https://fontawesome.com/search for icons options

subtitle: "De Sering: Start"
title: "Home for links and services"
logo: "/assets/logos/title_logo.png"
# logo: "/assets/title_logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon
header: true

footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars 
colors:
  light:
    highlight-primary: "#F3F0EB"
    highlight-secondary: "#FB3F2A"
    highlight-hover: "#EBEB47"
    background: "#FFFFFF"
    card-background: "#4A4D20"
    text: "#FFFFFF" # "Services" use this color, and this is a problem
    text-header: "#4A4D20"
    text-title: "#FFFFFF"
    text-subtitle: "#FFFFFF"
    card-shadow: rgba(251, 63, 42, .2)
    link: "#F3F0EB"
    link-hover: "#EBEB47"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  url: "https://github.com/desering/homer"
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Work in progress!"
  icon: "fa fa-grin"
  content: "This page is incomplete :S <br> Help with adding cards, adding icons, fixing style with the <b>\"improve this page\"</b> ↑ above!"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "improve this page"
    icon: "fa-solid fa-sliders"
    url: "https://github.com/desering/homer"
    # target: "_blank" # optional html a tag target attribute
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "De Sering community kitchen"
    icon: "fas fa-globe"
    items:
      - name: "De Sering website"
        url: "https://desering.org/"
      - name: "De Sering Facebook"
        url: "https://www.facebook.com/DeSeringAmsterdam"
      - name: "De Sering Instagram"
        url: "https://www.instagram.com/de_sering/"
      - name: "De Sering address"
        type: "CopyToClipboard"
        clipboard: "Rhôneweg 6, 1043 AH Amsterdam"
        subtitle: "Rhôneweg 6, 1043 AH Amsterdam"
        url: "https://maps.app.goo.gl/9XDVTJm8mhULWbdt6"
      - name: "De Sering street parking"
        type: "CopyToClipboard"
        clipboard: "Rhôneweg 6, 1043 AH Amsterdam"
        subtitle: "gemeente website, copy-paste address"
        url: "https://www.amsterdam.nl/parkeren/parkeertarieven/"


  - name: "De Sering Centraal"
    icon: "fas fa-globe"
    items:
      - name: "De Sering Centraal address"
        type: "CopyToClipboard"
        clipboard: "Dijksgracht 6, 1019 BS Amsterdam"
        subtitle: "Dijksgracht 6, 1019 BS Amsterdam"
        url: "https://maps.app.goo.gl/kzYJ6JwdLh3XjoMj9"
      - name: "De Sering Centraal street parking"
        type: "CopyToClipboard"
        clipboard: "Dijksgracht 6, 1019 BS Amsterdam"
        subtitle: "gemeente website, copy-paste address"
        url: "https://www.amsterdam.nl/parkeren/parkeertarieven/"