#s Homepage configuration
# See https://fontawesome.com/search for icons options

subtitle: "De Sering: Start"
title: "Home for links and services"
logo: "/assets/logos/title_logo.png"
header: true

footer: false

# Optional theme customization
theme: default

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars 
colors:
  light:
    highlight-primary: "#FFFFFF"
    highlight-secondary: "#FB3F2A"
    highlight-hover: "#EBEB47"
    background: "#FFFFFF"
    card-background: "#4A4D20"
    text: "#FFFFFF"
    text-header: "#4A4D20"
    text-title: "#FFFFFF"
    text-subtitle: "#FFFFFF"
    link: "#F3F0EB"
    link-hover: "#EBEB47"
    card-shadow: rgba(251, 63, 42, .2)
  dark:
    highlight-primary: "#000000"
    highlight-secondary: "#494C1A"
    highlight-hover: "#ECEB01"
    background: "#151515"
    card-background: "#2b2b2b"
    text: "#FFFFFF"
    text-header: "#F3F1EC"
    text-title: "#FFFFFF"
    text-subtitle: "#F3F1EC"
    link: "#FF3F00"
    link-hover: "#ECEB01"
    card-shadow: rgba(0, 0, 0, 0.4)

stylesheet:
   - "assets/customizations.css"

# Optional message
message:
  title: "Work in progress!"
  url: "https://github.com/desering/homer"
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  icon: "fa-solid fa-compass-drafting"
  content: "This page is incomplete :S <br> Help with adding cards, adding icons, fixing style with the <b>\"improve this page\"</b> ↑ above!"


# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "improve this page"
    icon: "fa-solid fa-sliders"
    url: "https://github.com/desering/homer"
    # target: "_blank" # optional html a tag target attribute
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Communication and Announcements"
    icon: "fa-regular fa-message"
    items:
      - name: "Schedule"
        icon: "fa-regular fa-calendar-days"
        subtitle: "Manage and discover volunteering shifts"
        url: "https://schedule.desering.org"
        tag: "self-made\n#self-hosted"
        quick:
          - name: "open source"
            url: "https://github.com/desering/volunteer-scheduler"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"

      - name: "Mattermost"
        subtitle: "Main forum for discussions"
        logo: "/assets/custom_media/Mattermost_icon_black.svg"
        url: "https://mattermost.desering.org/"
        tag: "self-hosted"

      - name: "WhatsApp community"
        subtitle: "Yet another WhatsApp group chat :)"
        icon: "fa-brands fa-whatsapp"
        url: "https://chat.whatsapp.com/IKoCe4CnZsdClRdutZ8soU"
        tag: "external"

  - name: "De Sering community kitchen"
    icon: "fas fa-globe"
    items:
      - name: "De Sering website"
        url: "https://desering.org/"
      - name: "De Sering Facebook"
        icon: "fa-brands fa-square-facebook"
        url: "https://www.facebook.com/DeSeringAmsterdam"
      - name: "De Sering Instagram"
        icon: "fa-brands fa-instagram"
        url: "https://www.instagram.com/de_sering/"
      - name: "De Sering address"
        type: "CopyToClipboard"
        clipboard: "Rhôneweg 6, 1043 AH Amsterdam"
        subtitle: "Rhôneweg 6, 1043 AH Amsterdam"
        icon: "fas fa-map-pin"
        url: "https://maps.app.goo.gl/9XDVTJm8mhULWbdt6"
      - name: "De Sering street parking"
        icon: "fa-solid fa-square-parking"
        type: "CopyToClipboard"
        clipboard: "Rhôneweg 6, 1043 AH Amsterdam"
        subtitle: "gemeente website, copy-paste address"
        url: "https://www.amsterdam.nl/parkeren/parkeertarieven/"

  - name: "De Sering Centraal"
    icon: "fas fa-globe"
    items:
      - name: "De Sering Centraal address"
        type: "CopyToClipboard"
        clipboard: "Dijksgracht 6, 1019 BS Amsterdam"
        subtitle: "Dijksgracht 6, 1019 BS Amsterdam"
        icon: "fas fa-map-pin"
        url: "https://maps.app.goo.gl/kzYJ6JwdLh3XjoMj9"
      - name: "De Sering Centraal street parking"
        icon: "fa-solid fa-square-parking"
        type: "CopyToClipboard"
        clipboard: "Dijksgracht 6, 1019 BS Amsterdam"
        subtitle: "gemeente website, copy-paste address"
        url: "https://www.amsterdam.nl/parkeren/parkeertarieven/"
   
  - name: "Resources and Knowledge"
    icon: "fa-solid fa-book-open-reader"
    items:
      - name: "Wiki"
        subtitle: "Documentation of internal operation and processes"
        icon: "fa-solid fa-book-atlas"
        url: "https://wiki.desering.org/"
        tag: "self-hosted"

      - name: "Brand kit"
        icon: "fa-solid fa-rectangle-ad"
        quick:
          - name: "Google Drive (PDF)"
            url: "https://drive.google.com/file/d/1p4rscjmGiYfOH-rpCIIFYlASEMg1_HZr/view?usp=drive_link"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"

  - name: "Technical and web tools"
    icon: "fa-solid fa-database"
    items:
      - name: "GitHub organization"
        subtitle: "The place to collaborate on tech projects"
        icon: "fab fa-github"
        url: "https://github.com/desering"

      - name: "Coolify"
        subtitle: "Our self-hosted Vercel alternative"
        logo: "/assets/logos/coolify.svg"
        url: "https://coolify.desering.org/"
        tag: "self-hosted"

      - name: "Identity provider for De Sering"
        subtitle: "SSO with Authentik"
        logo: "/assets/logos/authentik.png"
        url: "https://auth.desering.org/"
        tag: "self-hosted"

      - name: "One-Time Secret"
        subtitle: "Send secrets securely with OnetimeSecret"
        logo: "/assets/logos/onetimesecret.png"
        url: "https://onetimesecret.desering.org/"
        tag: "self-hosted"

      - name: "Grafana Cloud"
        subtitle: "Uptime Monitoring for self-hosted projects"
        logo: "/assets/logos/grafana.svg"
        url: "https://desering.grafana.net/"
        tag: "external"

      - name: "Vaultwarden"
        subtitle: "Password manager (Bitwarden compatible)"
        logo: "/assets/logos/vaultwarden.svg"
        url: "https://vaultwarden.desering.org/"
        tag: "self-hosted"
