name: publish

on:
  push:
    branches:
      - main

env:
  HOMER_VERSION_TAG: "v25.11.1"
  CONFIG_FILE_PATH: "config.yml"
  CSS_FILE_PATH: "customizations.css"
  DOWNLOADED_APP_PATH: "homer"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/configure-pages@v5

      - uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Download Homer Release artifact
        run: |
          wget https://github.com/bastienwirtz/homer/releases/download/${{ env.HOMER_VERSION_TAG }}/homer.zip
          
      - name: Unzip Homer Release artifact
        run: |
          unzip -q homer.zip -d ${{ env.DOWNLOADED_APP_PATH }}

      - name: Copy local config for deployment 
        run: |
          cp assets/${{ env.CONFIG_FILE_PATH }} ${{ env.DOWNLOADED_APP_PATH }}/assets/

      - name: Copy local style customizations for deployment
        run: cp assets/${{ env.CSS_FILE_PATH }} ${{ env.DOWNLOADED_APP_PATH }}/assets/

      - name: Copy logo
        run: |
          mkdir --parents ${{ env.DOWNLOADED_APP_PATH }}/assets/logos
          cp media/logos/de_sering_logo_red_with_text_translucent_binary_big.png ${{ env.DOWNLOADED_APP_PATH }}/assets/logos/title_logo.png

      - name: Clear old favicons
        run: |
          find ${{ env.DOWNLOADED_APP_PATH }}/assets/icons -type f -delete

      - uses: actions/setup-node@v4
        with:
          node-version: '20.18'

      - name: Generate new favicons
        run: |
          npx realfavicon generate ./media/logos/de_sering_logo_red_with_text_translucent_binary_big.png ./favicon-settings.json /dev/null ${{ env.DOWNLOADED_APP_PATH }}/assets/icons/

      - name: Rename favicons for Homer
        run: |
          cd ${{ env.DOWNLOADED_APP_PATH }}/assets/icons/
          mv *192x192.png pwa-192x192.png
          mv *512x512.png pwa-512x512.png

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ env.DOWNLOADED_APP_PATH }}/

  # Deploy job
  deploy:
    runs-on: ubuntu-latest

    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    # runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action        