name: deploy

on:
  push:
    branches:
      - main

env:
  HOMER_VERSION_TAG: v25.11.1
  CONFIG_FILE_PATH: "config.yaml"
  DOWNLOADED_APP_PATH: "homer"

jobs:
  deploy-zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Download ZIP artifact
        run: |
          wget https://github.com/bastienwirtz/homer/releases/download/${{ env.HOMER_VERSION_TAG }}/homer.zip
          
      - name: Unzip ZIP artifact
        run: |
          unzip homer.zip -d ${{ env.DOWNLOADED_APP_PATH }}

      - name: Copy local config for deployment 
        run: cp ${{ env.CONFIG_FILE_PATH }} ${{ env.DOWNLOADED_APP_PATH }}/